parameters:
- name: buildConfiguration
  type: string
  default: false
  values:
  - 'Release'
  - 'Debug'

- name: env
  type: string
  default: false
  values:
  - 'dev'
  - 'testing'
  - 'stage'

jobs:
- deployment: 'Deploy'
  displayName: 'Deploy on ${{ parameters.env }}'
  pool:
    vmImage: 'ubuntu-20.04'
  variables:
  - group: ${{ parameters.env }}
  environment: ${{ parameters.env }}
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: drop
        - task: AzureWebApp@1
          displayName: 'Azure App Service Deploy: website'
          inputs:
            azureSubscription: 'service-conn-tailspin-${{ parameters.env }}'
            appName: '$(WebAppName)'
            package: '$(Pipeline.Workspace)/drop/${{ parameters.buildConfiguration }}/Tailspin.SpaceGame.Web.zip'