parameters:
  - name: buildConfiguration
    type: string
    default: false
    values:
    - 'Release'
    - 'Debug'

  - name: env
    type: string
    default: false
    values:
    - 'dev'
    - 'testing'
    - 'stage'

jobs:
- deployment: Deploy
  displayName: 'Deploy ${{ env }}'
  pool:
    vmImage: 'ubuntu-20.04'
  variables:
  - group: ${{ env }}
  environment: ${{ env }}
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: drop
        - task: AzureWebApp@1
          displayName: 'Azure App Service Deploy: website'
          inputs:
            azureSubscription: 'service-conn-tailspin-${{ env }}'
            appName: '$(WebAppName)'
            package: '$(Pipeline.Workspace)/drop/${{ buildConfiguration }}/Tailspin.SpaceGame.Web.zip'